In [ ]:
# ----------------------------------------------------------------------------
# General Setup:

In [17]:
import pandas as pd

In [18]:
file_path = '../../files/output/faceiq_data.xlsx'
dfs = pd.read_excel(file_path, sheet_name=None)

artifacts_df = dfs['Pipeline Artifacts']
sizes_df = dfs['Detection Sizes']

artifacts_df = artifacts_df.astype(int)
sizes_df = sizes_df.astype(int)

In [ ]:
# ----------------------------------------------------------------------------
# Pipeline Artifacts:

In [20]:
artifacts_df.describe().round(2)

,idx,regions,face_detections,face_objs,source_objs,det_recognition_dfs
count,262.00,262.00,262.00,262.00,262.00,262.00
mean,2887.79,1.07,0.59,0.59,0.59,0.59
std,1795.13,0.25,0.75,0.75,0.75,0.75
min,0.00,1.00,0.00,0.00,0.00,0.00
25%,1305.00,1.00,0.00,0.00,0.00,0.00
50%,2610.00,1.00,0.00,0.00,0.00,0.00
75%,4515.00,1.00,1.00,1.00,1.00,1.00
max,5960.00,2.00,3.00,3.00,3.00,3.00

In [ ]:
# ----------------------------------------------------------------------------
# Detection Sizes:

In [22]:
sizes_df.describe().round(2)

           idx       w       h         a
count   154.00  154.00  154.00    154.00
mean   1861.69   47.58   69.33   4681.44
std    1679.26   33.20   43.30   8415.96
min       0.00   19.00   23.00    494.00
25%     565.00   29.00   43.50   1167.75
50%    1190.00   38.00   62.50   2365.00
75%    2715.00   48.75   68.00   3198.75
max    5820.00  247.00  274.00  67678.00

In [28]:
n_min_a = len(sizes_df.loc[sizes_df['a'] > (32*32)])
pcnt_min_a = round((n_min_a / len(sizes_df)), 2) * 100

print(f'{n_min_a} detections ({pcnt_min_a}% of total): area >= min area\n')

n_min_wh = len(sizes_df.loc[(sizes_df['w'] >= 32) & (sizes_df['h'] >= 32)])
pcnt_min_wh = round((n_min_wh / len(sizes_df)), 2) * 100

print(f"{n_min_wh} detections ({pcnt_min_wh}% of total): width AND height >= min side length\n")

123 detections (80.0% of total): area >= min area

103 detections (67.0% of total): width AND height >= min side length