In [ ]:
# ----------------------------------------------------------------------------
# General Setup:

In [1]:
import pandas as pd

In [4]:
file_path = '../../files/output/centerface_data.xlsx'
dfs = pd.read_excel(file_path, sheet_name=None)

detections_df = dfs['Detections']
artifacts_df = dfs['Pipeline Artifacts']

In [5]:
# ----------------------------------------------------------------------------
# Detections:

In [6]:
detections_df.describe().round(2)

           idx         a       c        x        y       w       h
count   232.00    232.00  232.00   232.00   232.00  232.00  232.00
mean   2125.52   3302.94    0.72  1306.55   327.69   41.59   62.17
std    1511.15   5307.60    0.12   486.21   152.97   23.54   32.23
min       0.00    462.00    0.50     2.00   190.00   16.00   22.00
25%     840.00   1313.00    0.62  1014.00   232.00   28.00   49.00
50%    1820.00   2262.50    0.74  1398.50   309.00   37.00   60.00
75%    3265.00   2884.50    0.82  1676.25   335.00   44.00   66.00
max    5540.00  36873.00    0.93  3194.00  1228.00  161.00  241.00

In [36]:
n_total = len(detections_df)

min_area = (32*32)
min_conf = 0.55

In [37]:
valid_area_detections = detections_df.loc[detections_df['a'] >= min_area]
valid_conf_detections = detections_df.loc[detections_df['c'] >= min_conf]
valid_a_c_detections = valid_area_detections.loc[valid_area_detections['c'] >= min_conf]

n_valid_area = len(valid_area_detections)
n_valid_conf = len(valid_conf_detections)
n_valid_a_c = len(valid_a_c_detections)

pct_valid_a = round((n_valid_area / n_total), 2) * 100
pct_valid_conf = round((n_valid_conf / n_total), 2) * 100
pct_valid_a_c = round((n_valid_a_c / n_total), 2) * 100

print(f'\n{n_valid_area} detections ({pct_valid_a}%): area >= min area\n')
print(f'{n_valid_conf} detections ({pct_valid_conf}%): confidence >= min confidence\n')
print(f'{n_valid_a_c} detections ({pct_valid_a_c}%): sufficient area AND confidence\n')

186 detections (80.0%): area >= min area

207 detections (89.0%): confidence >= min confidence

170 detections (73.0%): sufficient area AND confidence

In [ ]:
# ----------------------------------------------------------------------------
# Pipeline Artifacts:

In [ ]:
artifacts_df.describe().round(2)

           idx  face_detections  regions
count   286.00           286.00   286.00
mean   2850.00             0.81     1.04
std    1654.11             0.81     0.20
min       0.00             0.00     1.00
25%    1425.00             0.00     1.00
50%    2850.00             1.00     1.00
75%    4275.00             1.00     1.00
max    5700.00             3.00     2.00