In [ ]:
# ----------------------------------------------------------------------------
# General Setup:

In [2]:
import pandas as pd

In [3]:
file_path = '../../files/output/centerface_data.xlsx'
dfs = pd.read_excel(file_path, sheet_name=None)

artifacts_df = dfs['Pipeline Artifacts']
sizes_df = dfs['Detection Sizes']

In [ ]:
# ----------------------------------------------------------------------------
# Pipeline Artifacts:

In [6]:
artifacts_df.describe().round(2)

           idx  face_detections  regions
count   286.00           286.00   286.00
mean   2850.00             0.81     1.04
std    1654.11             0.81     0.20
min       0.00             0.00     1.00
25%    1425.00             0.00     1.00
50%    2850.00             1.00     1.00
75%    4275.00             1.00     1.00
max    5700.00             3.00     2.00

In [ ]:
# ----------------------------------------------------------------------------
# Detection Sizes:

In [7]:
sizes_df.describe().round(2)

           idx       w       h         a
count   232.00  232.00  232.00    232.00
mean   2125.52   41.59   62.17   3302.94
std    1511.15   23.54   32.23   5307.60
min       0.00   16.00   22.00    462.00
25%     840.00   28.00   49.00   1313.00
50%    1820.00   37.00   60.00   2262.50
75%    3265.00   44.00   66.00   2884.50
max    5540.00  161.00  241.00  36873.00

In [30]:
n_min_a = len(sizes_df.loc[sizes_df['a'] > (32*32)])
pcnt_min_a = round((n_min_a / len(sizes_df)), 2) * 100

print(f'{n_min_a} detections ({pcnt_min_a}% of total): area >= min area\n')

n_min_wh = len(sizes_df.loc[(sizes_df['w'] >= 32) & (sizes_df['h'] >= 32)])
pcnt_min_wh = round((n_min_wh / len(sizes_df)), 2) * 100

print(f"{n_min_wh} detections ({pcnt_min_wh}% of total): width AND height >= min side length\n")

186 detections (80.0% of total): area >= min area

149 detections (64.0% of total): width AND height >= min side length