In [ ]:
# ----------------------------------------------------------------------------
# General Setup:

In [1]:
import pandas as pd

In [2]:
file_path = '../../files/output/centerface_data.xlsx'
dfs = pd.read_excel(file_path, sheet_name=None)

detections_df = dfs['Detections']
artifacts_df = dfs['Pipeline Artifacts']

In [3]:
# ----------------------------------------------------------------------------
# Detections:

In [4]:
detections_df.describe().round(2)

           idx         a       c        x        y       w       h
count   207.00    207.00  207.00   207.00   207.00  207.00  207.00
mean   2148.31   3530.77    0.75  1323.12   330.42   43.13   64.00
std    1554.46   5571.85    0.10   500.51   160.26   24.28   33.34
min       0.00    570.00    0.55     2.00   196.00   19.00   26.00
25%     820.00   1386.00    0.67  1015.00   228.00   29.00   49.50
50%    1800.00   2380.00    0.75  1406.00   309.00   39.00   61.00
75%    3330.00   2913.00    0.82  1697.00   338.50   45.00   67.00
max    5540.00  36873.00    0.93  3194.00  1228.00  161.00  241.00

In [13]:
n_total = len(detections_df)

min_area = (32*32)
min_conf = 0.65

In [14]:
valid_area_detections = detections_df.loc[detections_df['a'] >= min_area]
valid_conf_detections = detections_df.loc[detections_df['c'] >= min_conf]
valid_a_c_detections = valid_area_detections.loc[valid_area_detections['c'] >= min_conf]

n_valid_area = len(valid_area_detections)
n_valid_conf = len(valid_conf_detections)
n_valid_a_c = len(valid_a_c_detections)

pct_valid_a = round((n_valid_area / n_total), 2) * 100
pct_valid_conf = round((n_valid_conf / n_total), 2) * 100
pct_valid_a_c = round((n_valid_a_c / n_total), 2) * 100

print(f'\n{n_valid_area} detections ({pct_valid_a}%): area >= min area\n')
print(f'{n_valid_conf} detections ({pct_valid_conf}%): confidence >= min confidence\n')
print(f'{n_valid_a_c} detections ({pct_valid_a_c}%): sufficient area AND confidence\n')

170 detections (82.0%): area >= min area

163 detections (79.0%): confidence >= min confidence

136 detections (66.0%): sufficient area AND confidence

In [ ]:
# ----------------------------------------------------------------------------
# Pipeline Artifacts:

In [ ]:
artifacts_df.describe().round(2)

           idx  face_detections  regions
count   286.00           286.00   286.00
mean   2850.00             0.81     1.04
std    1654.11             0.81     0.20
min       0.00             0.00     1.00
25%    1425.00             0.00     1.00
50%    2850.00             1.00     1.00
75%    4275.00             1.00     1.00
max    5700.00             3.00     2.00