In [ ]:
# ----------------------------------------------------------------------------
# General Setup:

In [1]:
import pandas as pd

In [2]:
file_path = '../../files/output/faceiq_data.xlsx'
dfs = pd.read_excel(file_path, sheet_name=None)

detections_df = dfs['Detections']
artifacts_df = dfs['Pipeline Artifacts']

In [3]:
# ----------------------------------------------------------------------------
# Detections:

In [4]:
detections_df.describe().round(2)

           idx         a       c        x       y       w       h
count   154.00    154.00  154.00   154.00  154.00  154.00  154.00
mean   1861.69   4681.44    0.72   642.69  405.99   47.58   69.33
std    1679.26   8415.96    0.12   415.70  147.65   33.20   43.30
min       0.00    494.00    0.50    79.00   66.00   19.00   23.00
25%     565.00   1167.75    0.63   354.75  300.75   29.00   43.50
50%    1190.00   2365.00    0.73   594.50  376.00   38.00   62.50
75%    2715.00   3198.75    0.82   799.50  467.75   48.75   68.00
max    5820.00  67678.00    0.94  2539.00  866.00  247.00  274.00

In [15]:
n_total = len(detections_df)

min_area = (32*32)
min_conf = 0.55

In [16]:
valid_area_detections = detections_df.loc[detections_df['a'] >= min_area]
valid_conf_detections = detections_df.loc[detections_df['c'] >= min_conf]
valid_a_c_detections = valid_area_detections.loc[valid_area_detections['c'] >= min_conf]

n_valid_area = len(valid_area_detections)
n_valid_conf = len(valid_conf_detections)
n_valid_a_c = len(valid_a_c_detections)

pct_valid_a = round((n_valid_area / n_total), 2) * 100
pct_valid_conf = round((n_valid_conf / n_total), 2) * 100
pct_valid_a_c = round((n_valid_a_c / n_total), 2) * 100

print(f'\n{n_valid_area} detections ({pct_valid_a}%): area >= min area\n')
print(f'{n_valid_conf} detections ({pct_valid_conf}%): confidence >= min confidence\n')
print(f'{n_valid_a_c} detections ({pct_valid_a_c}%): sufficient area AND confidence\n')

123 detections (80.0%): area >= min area

138 detections (90.0%): confidence >= min confidence

112 detections (73.0%): sufficient area AND confidence

In [8]:
# ----------------------------------------------------------------------------
# Pipeline Artifacts:

In [9]:
artifacts_df.describe().round(2)

,idx,regions,face_detections,face_objs,source_objs,det_recognition_dfs
count,262.00,262.00,262.00,262.00,262.00,262.00
mean,2887.79,1.07,0.59,0.59,0.59,0.59
std,1795.13,0.25,0.75,0.75,0.75,0.75
min,0.00,1.00,0.00,0.00,0.00,0.00
25%,1305.00,1.00,0.00,0.00,0.00,0.00
50%,2610.00,1.00,0.00,0.00,0.00,0.00
75%,4515.00,1.00,1.00,1.00,1.00,1.00
max,5960.00,2.00,3.00,3.00,3.00,3.00